export const getRollFields = (countries, rollTypes, rollQualities) => [
  {
    type: "text",
    label: "Roll Code",
    name: "rollCode",
    placeholder: "Roll code",
    column: "left",
  },
  {
    type: "number",
    label: "Thickness",
    name: "thickness",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "number",
    label: "Width",
    name: "width",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "number",
    label: "Net Weight",
    name: "netWeight",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "number",
    label: "Gross Weight",
    name: "grossWeight",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "number",
    label: "Theory Length",
    name: "theoryLength",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "number",
    label: "Actual Length",
    name: "actualLength",
    placeholder: "100",
    min: 0,
    column: "left",
  },
  {
    type: "select",
    label: "Made In",
    name: "madeInId",
    options: countries.map((country) => ({
      value: country.id,
      label: country.country,
    })),
    column: "right",
  },
  {
    type: "select",
    label: "Quality",
    name: "qualityId",
    options: rollQualities.map((quality) => ({
      value: quality.id,
      label: quality.quality,
    })),
    column: "right",
  },
  {
    type: "select",
    label: "Type",
    name: "typeId",
    options: rollTypes.map((type) => ({
      value: type.id,
      label: type.type,
    })),
    column: "right",
  },
  // {
  //   type: "text",
  //   label: "Image",
  //   name: "img",
  //   placeholder: "Image URL",
  //   column: "right",
  // },
  {
    type: "textarea",
    label: "Comment",
    name: "comment",
    placeholder: "Comment",
    column: "right",
  },
];
